class Enemy
  attr_accessor power: untyped

  attr_accessor position: untyped

  attr_accessor color: untyped

  attr_accessor radius_spawn: untyped

  def initialize: (?::Integer init_health, ?::Integer radius_spawn, ?::Integer power) -> void

  def load: (untyped position, untyped color) -> untyped

  def spawn: (untyped position_player, untyped difficult_game) -> untyped

  def do: (untyped position_player) -> (::FalseClass | ::TrueClass)

  def dead?: () -> (::TrueClass | ::FalseClass)

  def take_damage: (untyped power) -> untyped
end
