class Player
  attr_accessor command: untyped

  attr_accessor position: untyped

  attr_accessor health: untyped

  attr_accessor ray_direction: untyped

  attr_accessor angle_rotation: untyped

  attr_accessor power: untyped

  attr_accessor angle_x: untyped

  def initialize: (?::Integer health, ?::Integer power, ?untyped position, ?::Float angle_rotation) -> void

  def trans: () -> untyped

  def dead?: () -> untyped

  def take_damage: (untyped power) -> untyped

  def intersect_enemy: (untyped position) -> untyped

  def do: (untyped key, untyped enemies) -> (untyped | ::Array[::TrueClass | untyped])
end
