class Setting
  attr_accessor health_enemy: untyped

  attr_accessor power_enemy: untyped

  attr_accessor spawn_time_enemy: untyped

  attr_accessor min_enemies: untyped

  attr_accessor path_to_mesh_enemy: untyped

  attr_accessor difficult_game: untyped

  attr_accessor radius_spawn: untyped

  attr_accessor on_render: untyped

  def initialize: (?::Integer health_enemy, ?::Integer power_enemy, ?::Integer spawn_time_enemy, ?::Integer min_enemies, ?::Integer path_to_mesh_enemy, ?::Integer radius_spawn, ?::Integer difficult_game, ?::Integer on_render) -> void
end
