class Continue < State
  def initialize: (?::String statenext) -> void

  def s_key: () -> (::String | "up" | "down")

  def s_key_timeout: (untyped time) -> untyped

  def print_menu: () -> untyped

  def name_saves: () -> untyped

  def do: () -> untyped

  def next: () -> untyped
end
